# Задание 1

### Создайте массив NumPy размером 3×3, содержащий числа от 1 до 9. Умножьте все элементы массива на 2, а затем замените все элементы больше 10 на 0. Выведите итоговый массив.

In [1]:
import numpy as np

arr = np.arange(1, 10).reshape(3,3)
arr *= 2
arr[arr > 10] = 0
print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


# Задание 2

### Создайте массив NumPy из 20 случайных целых чисел от 1 до 100. Найдите и выведите все элементы, которые делятся на 5 без остатка. Затем замените их на -1 и выведите обновленный массив.

In [13]:
arr = np.random.randint(1, 101, size=20)
print(f"Исходный массив: {arr}")
divide_by_5 = arr[arr % 5 == 0]
print(f"Элементы массива, которые делятся на 5 без остатка: {divide_by_5}")
arr[arr % 5 == 0] = -1
print(f"Обновленный массив: {arr}")

Исходный массив: [67 64  4 83 42 10 23 92 91 72 99 33 92 33 40 41 98 92  5 97]
Элементы массива, которые делятся на 5 без остатка: [10 40  5]
Обновленный массив: [67 64  4 83 42 -1 23 92 91 72 99 33 92 33 -1 41 98 92 -1 97]


# Задание 3

### Создайте два массива NumPy размером 1×5, заполненные случайными числами от 0 до 50. Объедините эти массивы в один двумерный массив (по строкам). Разделите полученный массив на два массива, каждый из которых содержит 5 элементов. Выведите все промежуточные и итоговые результаты.

In [12]:
arr1 = np.random.randint(0, 51, size=(1, 5))
arr2 = np.random.randint(0, 51, size=(1, 5))

print("Первый массив:", arr1)
print("Второй массив:", arr2)

combined = np.vstack((arr1, arr2))
print("Объединённый двумерный массив:\n", combined)

split1, split2 = np.vsplit(combined, 2)
print("Первый разделённый массив:", split1)
print("Второй разделённый массив:", split2)

Первый массив: [[13 28  6 18 18]]
Второй массив: [[44  5 20 43 13]]
Объединённый двумерный массив:
 [[13 28  6 18 18]
 [44  5 20 43 13]]
Первый разделённый массив: [[13 28  6 18 18]]
Второй разделённый массив: [[44  5 20 43 13]]


# Задание 4

### Создайте массив из 50 чисел, равномерно распределенных от -10 до 10. Вычислите сумму всех элементов, сумму положительных элементов и сумму отрицательных элементов. Выведите результаты.

In [14]:
arr = np.linspace(-10, 10, 50)
print(arr)

arr_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

print("\nСумма всех элементов:", arr_sum)
print("Сумма положительных элементов:", positive_sum)
print("Сумма отрицательных элементов:", negative_sum)

[-10.          -9.59183673  -9.18367347  -8.7755102   -8.36734694
  -7.95918367  -7.55102041  -7.14285714  -6.73469388  -6.32653061
  -5.91836735  -5.51020408  -5.10204082  -4.69387755  -4.28571429
  -3.87755102  -3.46938776  -3.06122449  -2.65306122  -2.24489796
  -1.83673469  -1.42857143  -1.02040816  -0.6122449   -0.20408163
   0.20408163   0.6122449    1.02040816   1.42857143   1.83673469
   2.24489796   2.65306122   3.06122449   3.46938776   3.87755102
   4.28571429   4.69387755   5.10204082   5.51020408   5.91836735
   6.32653061   6.73469388   7.14285714   7.55102041   7.95918367
   8.36734694   8.7755102    9.18367347   9.59183673  10.        ]

Сумма всех элементов: 7.105427357601002e-15
Сумма положительных элементов: 127.55102040816328
Сумма отрицательных элементов: -127.55102040816327


# Задание 5

### Создайте: Единичную матрицу размером 4×4. Диагональную матрицу размером 4×4 с диагональными элементами [5, 10, 15, 20] (не использовать циклы). Найдите сумму всех элементов каждой из этих матриц и сравните результаты.

In [19]:
ed = np.eye(4)
diag = np.diag([5, 10, 15, 20])

sum_ed = np.sum(ed)
sum_diag = np.sum(diag)

print("Сумма элементов единичной матрицы:", sum_ed)
print("Сумма элементов диагональной матрицы:", sum_diag)

if sum_ed > sum_diag:
    print("Сумма элементов единичной матрицы больше")
elif sum_ed < sum_diag:
    print("Сумма элементов диагональной матрицы больше")
else:
    print("Суммы равны")

Сумма элементов единичной матрицы: 4.0
Сумма элементов диагональной матрицы: 50
Сумма элементов диагональной матрицы больше


# Задание 6

### Создайте две квадратные матрицы NumPy размером 3×3, заполненные случайными целыми числами от 1 до 20. Вычислите и выведите: Их сумму, их разность, их поэлементное произведение.

In [20]:
A1 = np.random.randint(1, 21, size=(3, 3))
A2 = np.random.randint(1, 21, size=(3, 3))

print("Матрица 1:\n", A1)
print("Матрица 2:\n", A2)

print("Сумма:\n", A1 + A2)
print("Разность:\n", A1 - A2)
print("Поэлементное произведение:\n", A1 * A2)

Матрица 1:
 [[10 16 12]
 [ 5  4 14]
 [19 17  7]]
Матрица 2:
 [[ 9 14 16]
 [ 7 18 13]
 [10 15 18]]
Сумма:
 [[19 30 28]
 [12 22 27]
 [29 32 25]]
Разность:
 [[  1   2  -4]
 [ -2 -14   1]
 [  9   2 -11]]
Поэлементное произведение:
 [[ 90 224 192]
 [ 35  72 182]
 [190 255 126]]


# Задание 7

### Создайте две матрицы NumPy: Первую размером 2×3, заполненную случайными числами от 1 до 10. Вторую размером 3×2, заполненную случайными числами от 1 до 10. Выполните матричное умножение (@ или nр. dot ) и выведите результат.

In [25]:
A = np.random.randint(1, 11, size=(2, 3))
B = np.random.randint(1, 11, size=(3, 2))
print("Первая матрица:\n", A)
print("Вторая матрица:\n", B)

result = np.dot(A, B)

print("Результат матричного умножения\n", result)

Первая матрица:
 [[ 2  1 10]
 [ 9  3  3]]
Вторая матрица:
 [[ 7  9]
 [ 2 10]
 [ 6  5]]
Результат матричного умножения
 [[ 76  78]
 [ 87 126]]


# Задание 8

### Создайте случайную квадратную матрицу 3×3. Найдите и выведите: Определитель этой матрицы, Обратную матрицу (если существует, иначе выведите сообщение, что матрица вырождена). Используйте функции np.linalg.det и nр.linalg.inv.

In [26]:
A = np.random.rand(3, 3)
print("Случайная матрица:\n", A)

A_det = round(np.linalg.det(A), 3)
print("\nОпределитель матрицы", A_det)

if A_det == 0:
    print("\nМатрица вырождена!")
else:
    A_inv = np.linalg.inv(A)
    print("\nОбратная матрица:\n", A_inv)

Случайная матрица:
 [[0.35302239 0.22072437 0.49167505]
 [0.3053935  0.95576524 0.52406803]
 [0.21839495 0.12046771 0.73713118]]

Определитель матрицы 0.117

Обратная матрица:
 [[ 5.46054928 -0.88091826 -3.0159554 ]
 [-0.94212605  1.3012571  -0.29672788]
 [-1.46386515  0.04833419  2.2986622 ]]


# Задание 9

### Создайте матрицу NumPy размером 4×4, содержащую случайные целые числа от 1 до 50. Выведите: Исходную матрицу, Транспонированную матрицу, След матрицы (сумму элементов на главной диагонали). Используйте np.trace для нахождения следа.

In [27]:
A = np.random.randint(1, 51, size = (4, 4))
A_t = np.transpose(A)
A_trace = np.trace(A)

print("Исходная матрица:\n", A)
print("Транспонированная матрица:\n", A_t)
print("След матрицы:\n", A_trace)

Исходная матрица:
 [[19  2 18 45]
 [ 2 15 28 10]
 [34 15 48 46]
 [ 7 45  3 39]]
Транспонированная матрица:
 [[19  2 34  7]
 [ 2 15 15 45]
 [18 28 48  3]
 [45 10 46 39]]
След матрицы:
 121


# Задание 10

### Решите систему линейных уравнений вида: 
$2x + 3y - z = 5$<br>
$4x - y + 2z = 6$<br>
$-3x + 5y + 4z = -2$

In [28]:
A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

x = np.linalg.solve(A, B)
print("Решение системы (x, y, z):", x)

Решение системы (x, y, z): [1.63963964 0.57657658 0.00900901]


# Индивидуальное задание

### Задание предусматривает построение системы линейных уравнений. Решите полученную систему уравнений с использованием библиотеки NumPy. Для решения системы используйте метод Крамера и матричный метод. Сравните полученные результаты, с результатами, полученными с помощью np.linalg.solve.

### **Условие**: Распределение электроэнергии. Город получает электроэнергию от трех электростанций. Первая станция дает в два раза больше энергии, чем вторая, а третья - на 200 МВт больше, чем вторая. Всего требуется 1500 МВт. Сколько электроэнергии должно поступать с каждой станции?

### **Решение**: Пусть x1, x2, x3 - мощности (МВт) первой, второй, третьей станций соответственно.
$x1 = x2 * 2$ <br>
$x3 = x2 + 200$ <br>
$x1 + x2 + x3 = 1500$ <br>
### Получаем систему уравнений:
$x1 – x2 * 2 = 0$ <br>
$x3 – x2 = 200$ <br>
$x1 + x2 + x3 = 1500$ <br>

In [29]:
A = np.array([
    [1, -2, 0],
    [0, -1, 1],
    [1, 1, 1]
])
B = np.array([0, 200, 1500])

A_det = np.linalg.det(A)
if A_det == 0:
    print("Матрица вырождена, метод Крамера неприменим.")
else:
    x_cramer = []
    for i in range(3):
        Ai = A.copy()
        Ai[:, i] = B
        Ai_det = np.linalg.det(Ai)
        x_cramer.append(Ai_det / A_det)
    x_cramer = np.array(x_cramer)
    print("Метод Крамера:", x_cramer)

if A_det == 0:
    print("Матрица вырождена, обратная матрица не существует.")
else:
    A_inv = np.linalg.inv(A)
    x_inv = np.dot(A_inv, B)
    print("Матричный метод:", x_inv)

x_solve = np.linalg.solve(A, B)
print("np.linalg.solve:", x_solve)

print("\nВсе методы дают одинаковый результат (x1, x2, x3):")
print(f"x1 = {x_solve[0]}, x2 = {x_solve[1]}, x3 = {x_solve[2]}")

Метод Крамера: [650. 325. 525.]
Матричный метод: [650. 325. 525.]
np.linalg.solve: [650. 325. 525.]

Все методы дают одинаковый результат (x1, x2, x3):
x1 = 650.0, x2 = 325.0, x3 = 525.0
