In [1]:
import numpy as np

A1 = np.random.randint(1, 21, size=(3, 3))
A2 = np.random.randint(1, 21, size=(3, 3))

print("Матрица 1:\n", A1)
print("Матрица 2:\n", A2)

print("Сумма:\n", A1 + A2)
print("Разность:\n", A1 - A2)
print("Поэлементное произведение:\n", A1 * A2)

Матрица 1:
 [[ 9  2  2]
 [ 6 14  6]
 [ 6  5 11]]
Матрица 2:
 [[ 7  8 15]
 [ 1 17  7]
 [ 2  4  1]]
Сумма:
 [[16 10 17]
 [ 7 31 13]
 [ 8  9 12]]
Разность:
 [[  2  -6 -13]
 [  5  -3  -1]
 [  4   1  10]]
Поэлементное произведение:
 [[ 63  16  30]
 [  6 238  42]
 [ 12  20  11]]
