In [8]:
import numpy as np

A = np.random.randint(1, 11, size=(2, 3))
B = np.random.randint(1, 11, size=(3, 2))
print("Первая матрица:\n", A)
print("Вторая матрица:\n", B)

result = np.dot(A, B)

print("Результат матричного умножения\n", result)

Первая матрица:
 [[7 4 2]
 [4 1 4]]
Вторая матрица:
 [[ 5  9]
 [ 8  8]
 [10  9]]
Результат матричного умножения
 [[ 87 113]
 [ 68  80]]
