In [5]:
import numpy as np

A = np.random.rand(3, 3)
print("Случайная матрица:\n", A)

A_det = round(np.linalg.det(A), 3)
print("\nОпределитель матрицы", A_det)

if A_det == 0:
    print("\nМатрица вырождена!")
else:
    A_inv = np.linalg.inv(A)
    print("\nОбратная матрица:\n", A_inv)

Случайная матрица:
 [[0.60251541 0.97619503 0.99440634]
 [0.53962837 0.36543589 0.73280125]
 [0.53085885 0.35565058 0.27344496]]

Определитель матрицы 0.137

Обратная матрица:
 [[-1.17447534  0.63385494  2.57242277]
 [ 1.76473512 -2.6540573   0.69495779]
 [-0.01517103  2.22139592 -2.24087339]]
