In [2]:
import numpy as np

A = np.random.randint(1, 51, size = (4, 4))
A_t = np.transpose(A)
A_trace = np.trace(A)

print("Исходная матрица:\n", A)
print("Транспонированная матрица:\n", A_t)
print("След матрицы:\n", A_trace)

Исходная матрица:
 [[42  7 28  7]
 [32 18 36 23]
 [42 11 39 28]
 [17 49 47 50]]
Транспонированная матрица:
 [[42 32 42 17]
 [ 7 18 11 49]
 [28 36 39 47]
 [ 7 23 28 50]]
След матрицы:
 149
