In [1]:
import numpy as np
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [2]:
print(np.arange(5, 12))

[ 5  6  7  8  9 10 11]


In [3]:
print(np.arange(1, 5, 0.5))

[1.  1.5 2.  2.5 3.  3.5 4.  4.5]
