In [1]:
import numpy as np
a = [[1, 2], [3, 4]]
print(np.matrix(a))

[[1 2]
 [3 4]]


In [2]:
b = np.array([[5, 6], [7, 8]])
print(np.matrix(b))

[[5 6]
 [7 8]]


In [5]:
c = np.matrix('[1, 2; 3, 4]')
print(c)

[[1 2]
 [3 4]]
