In [1]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
print(np.ravel(A))

[1 2 3 4 5 6 7 8 9]


In [6]:
print(np.ravel(A, order='C'))

[1 2 3 4 5 6 7 8 9]


In [7]:
print(np.ravel(A, order='F'))

[1 4 7 2 5 8 3 6 9]
