In [1]:
import numpy as np
print(np.random.permutation(7))
a = ['a', 'b', 'c', 'd', 'e']
print(np.random.permutation(a))

[4 5 3 0 2 1 6]
['e' 'c' 'b' 'd' 'a']


In [2]:
arr = np.linspace(0, 10, 5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [3]:
arr_mix = np.random.permutation(arr)
print(arr_mix)

[ 0.  10.   7.5  5.   2.5]


In [5]:
index_mix = np.random.permutation(len(arr_mix))
print(index_mix)
print(arr[index_mix])

[2 3 1 4 0]
[ 5.   7.5  2.5 10.   0. ]
