In [1]:
import numpy as np
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
m_sqr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
m_sqr_arr2 = np.array(m_sqr)
print(m_sqr_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m_sqr_mx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
m_sqr_mx2 = np.matrix('1 2 3; 4 5 6; 7 8 9')
print(m_sqr_mx2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
