In [2]:
import numpy as np
A = np.matrix('1 2 3; 4 5 6')
print(A)

[[1 2 3]
 [4 5 6]]


In [3]:
A_t = A.transpose()
print(A_t)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
R = (A.T).T
print(R)

[[1 2 3]
 [4 5 6]]


In [7]:
B = np.matrix('7 8 9; 0 7 5')
L = (A + B).T
R2 = A.T + B.T
print(L)
print(R2)

[[ 8  4]
 [10 12]
 [12 11]]
[[ 8  4]
 [10 12]
 [12 11]]


In [9]:
C = np.matrix('1 2; 3 4')
D = np.matrix('5 6; 7 8')
L2 = (C.dot(D)).T
R3 = (D.T).dot(C.T)
print(L2)
print(R3)

[[19 43]
 [22 50]]
[[19 43]
 [22 50]]


In [10]:
k = 3
L3 = (k * A).T
R4 = k * (A.T)
print(L3)
print(R4)

[[ 3 12]
 [ 6 15]
 [ 9 18]]
[[ 3 12]
 [ 6 15]
 [ 9 18]]


In [11]:
C_det = np.linalg.det(C)
C_T_det = np.linalg.det(C.T)
print(f"{C_det:.9f}")
print(f"{C_T_det:.9f}")

-2.000000000
-2.000000000
