In [1]:
import numpy as np
A = np.matrix('1 2 3; 4 5 6')
C = 3 * A
print(C)

[[ 3  6  9]
 [12 15 18]]


In [2]:
B = np.matrix('1 2; 3 4')
L = 1 * B
R = B
print(L)
print(R)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [4]:
Z = np.matrix('0 0; 0 0')
L2 = 0 * B
R2 = Z
print(L2)
print(R2)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


In [5]:
p = 2
q = 3
L3 = (p + q) * B
R3 = p * B + q * B
print(L3)
print(R3)

[[ 5 10]
 [15 20]]
[[ 5 10]
 [15 20]]


In [6]:
L4 = (p * q) * B
R4 = p * (q * B)
print(L4)
print(R4)

[[ 6 12]
 [18 24]]
[[ 6 12]
 [18 24]]


In [7]:
C = np.matrix('5 6; 7 8')
k = 3
L5 = k * (B + C)
R5 = k * B + k * C
print(L5)
print(R5)

[[18 24]
 [30 36]]
[[18 24]
 [30 36]]
