In [3]:
import numpy as np
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = A + B
print(C)

[[ 6  8]
 [10 12]]


In [4]:
C2 = B + A
print(C)
print(C2)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [5]:
C = np.matrix('1 7; 9 3')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[ 7 15]
 [19 15]]
[[ 7 15]
 [19 15]]


In [6]:
Z = np.matrix('0 0; 0 0')
L2 = A + (-1)*A
print(L2)
print(Z)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
