In [4]:
import numpy as np
A = np.matrix('1 2; 3 4')
B = np.matrix('5 6; 7 8')
C = np.matrix('2 4; 7 8')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[192 252]
 [436 572]]
[[192 252]
 [436 572]]


In [5]:
L2 = A.dot(B + C)
R2 = A.dot(B) + A.dot(C)
print(L2)
print(R2)

[[35 42]
 [77 94]]
[[35 42]
 [77 94]]


In [6]:
L3 = A.dot(B)
R3 = B.dot(A)
print(L3)
print(R3)

[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


In [7]:
E = np.matrix('1 0; 0 1')
I = E.dot(A)
Q = A.dot(E)
print(I)
print(Q)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [8]:
Z = np.matrix('0 0; 0 0')
I2 = Z.dot(A)
Q2 = A.dot(Z)
print(I2)
print(Q2)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]
