In [1]:
import numpy as np
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
print(A)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]


In [3]:
print(np.linalg.det(A))

-14.000000000000009


In [5]:
print(A)
print(A.T)
det_A = round(np.linalg.det(A), 3)
det_A_t = round(np.linalg.det(A.T), 3)
print(det_A)
print(det_A_t)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 10  8]
 [-1  4  3]
 [ 2 -1  1]]
-14.0
-14.0


In [6]:
B = np.matrix('-4 -1 2; 0 0 0; 8 3 1')
print(B)
print(np.linalg.det(B))

[[-4 -1  2]
 [ 0  0  0]
 [ 8  3  1]]
0.0


In [7]:
C = np.matrix('10 4 -1; -4 -1 2; 8 3 1')
print(A)
print(C)
print(round(np.linalg.det(A), 3))
print(round(np.linalg.det(C), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[10  4 -1]
 [-4 -1  2]
 [ 8  3  1]]
-14.0
14.0


In [8]:
D = np.matrix('-4 -1 2; -4 -1 2; 8 3 1')
print(D)
print(np.linalg.det(D))

[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
0.0


In [9]:
print(A)
k = 2
E = A.copy()
E[2, :] = k * E[2, :]
print(E)
det_E = round(np.linalg.det(E), 3)
print(det_A * k)
print(det_E)

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [10  4 -1]
 [16  6  2]]
-28.0
-28.0


In [10]:
F = np.matrix('-4 -1 2; 8 3 2; 8 3 1')
G = D.copy()
G[1, :] += F[1, :]
print(G)
print(D)
print(F)
print(round(np.linalg.det(G), 3))
print(round(np.linalg.det(D), 3) + (round(np.linalg.det(F), 3)))

[[-4 -1  2]
 [ 4  2  4]
 [ 8  3  1]]
[[-4 -1  2]
 [-4 -1  2]
 [ 8  3  1]]
[[-4 -1  2]
 [ 8  3  2]
 [ 8  3  1]]
4.0
4.0
