In [1]:
import numpy as np
A = np.matrix('-4 -1 2; 10 4 -1; 8 3 1')
k = 2
B = A.copy()
B[1, :] = B[1, :] + k * B[0, :]
print(A)
print(B)
print(round(np.linalg.det(A), 3))
print(round(np.linalg.det(B), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
[[-4 -1  2]
 [ 2  2  3]
 [ 8  3  1]]
-14.0
-14.0


In [2]:
print(A)
A[1, :] = A[0, :] + k * A[2, :]
print(round(np.linalg.det(A), 3))

[[-4 -1  2]
 [10  4 -1]
 [ 8  3  1]]
0.0
