In [2]:
import numpy as np
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [3]:
print(m[1, 0])

5


In [4]:
print(m[1, :])

[[5 6 7 8]]


In [5]:
print(m[:, 2])

[[3]
 [7]
 [5]]


In [6]:
print(m[1, 2:])

[[7 8]]


In [7]:
print(m[0:2, 1])

[[2]
 [6]]


In [8]:
print(m[0:2, 1:3])

[[2 3]
 [6 7]]


In [10]:
cols = [0, 1, 3]
print(m[:, cols])

[[1 2 4]
 [5 6 8]
 [9 1 7]]


In [11]:
print(type(m))

<class 'numpy.matrix'>


In [12]:
m = np.array(m)
print(type(m))

<class 'numpy.ndarray'>


In [13]:
print(m.shape)

(3, 4)


In [15]:
print(m.max())

9


In [16]:
print(np.max(m))

9


In [17]:
print(m.max(axis=1))

[4 8 9]


In [18]:
print(m.max(axis=0))

[9 6 7 8]


In [19]:
print(m.mean())
print(m.mean(axis=1))
print(m.sum())
print(m.sum(axis=0))

4.833333333333333
[2.5 6.5 5.5]
58
[15  9 15 19]
